const express = require('express');
const router = express.Router();
const campaignController = require('../controllers/campaign.controller');
const upload = require('../middlewares/multer.middle');
const auth=require('../middlewares/auth.middle');
const role=require('../middlewares/role.middle');
const setImageType = require('../middlewares/TypeImage.middle');
router.post('/create',auth.verifyToken,role.checkRole(['admin'],true),setImageType("campaign"),upload.single('image') ,campaignController.createCampaign);
router.get('/all', auth.verifyToken,role.checkRole(["donor", "beneficiary", "volunteer", "admin"],true),campaignController.getAllCampaigns);
router.get('/featured', auth.verifyToken,role.checkRole(['admin'],true),campaignController.getFeaturedCampaigns);
router.get('/:id',auth.verifyToken,role.checkRole(["donor", "beneficiary", "volunteer", "admin"],true),campaignController.getCampaignById);
router.put('/:id',auth.verifyToken,role.checkRole(['admin'],true),setImageType("campaign"),upload.single('image'), campaignController.updateCampaign);
router.delete('/:id',auth.verifyToken,role.checkRole(['admin'],true), campaignController.deleteCampaign);
router.put('/mark-featured/:id',auth.verifyToken,role.checkRole(['admin']),campaignController.markAsFeatured);
router.post('/statusCampaign/:id',auth.verifyToken,role.checkRole(['admin']),campaignController.statusCampaign);
router.post('/addVolunteer/:id/:campaignId',auth.verifyToken,role.checkRole(['admin','volunteer'],true),campaignController.addVolunteers);
router.post('/removeVolunteer/:id/:campaignId',auth.verifyToken,role.checkRole(['admin'],true),campaignController.leaveVolunteers);
router.post('/:donationId/:campaignId',auth.verifyToken,role.checkRole(['admin','donor']),campaignController.addDonation);
router.post('/addBeneficiary/:id',auth.verifyToken,role.checkRole(['admin'],true),campaignController.addBeneficiary);
router.post('/removeBeneficiary/:id',auth.verifyToken,role.checkRole(['admin'],true),campaignController.removeBeneficiary);
router.get('/join/:id',auth.verifyToken,role.checkRole(["donor", "beneficiary", "volunteer", "admin"],true),campaignController.JoinCampaign);
module.exports = router;